<?php

global $routes;
$routes = array();

$routes['/categoria/{slug}'] = '/categories/category/:slug';
$routes['/categorias/{slug}'] = '/categories/categories/:slug';
$routes['/marcas/{slug}'] = '/brands/enter/:slug';

$routes['/lustres-e-pendentes/{slug}'] = '/product/open/:slug';
$routes['/lustres-e-pendentes-cristal/{slug}'] = '/product/open/:slug';
$routes['/lustres-e-pendentes-aluminio-metal/{slug}'] = '/product/open/:slug';
$routes['/lustres-e-pendentes-tecido/{slug}'] = '/product/open/:slug';
$routes['/lustres-e-pendentes-vidro/{slug}'] = '/product/open/:slug';
$routes['/lustres-e-pendentes-madeira/{slug}'] = '/product/open/:slug';
$routes['/lustres-e-pendentes-acrilico/{slug}'] = '/product/open/:slug';
$routes['/arandelas-e-balizadores/{slug}'] = '/product/open/:slug';
$routes['/arandelas-e-balizadores-internos/{slug}'] = '/product/open/:slug';
$routes['/arandelas-e-balizadores-externos/{slug}'] = '/product/open/:slug';
$routes['/plafon/{slug}'] = '/product/open/:slug';
$routes['/plafon-sobrepor/{slug}'] = '/product/open/:slug';
$routes['/plafon-embutir/{slug}'] = '/product/open/:slug';
$routes['/spots/{slug}'] = '/product/open/:slug';
$routes['/spots-sobrepor/{slug}'] = '/product/open/:slug';
$routes['/spots-embutir/{slug}'] = '/product/open/:slug';
$routes['/linha-led/{slug}'] = '/product/open/:slug';
$routes['/plafon-linha-led/{slug}'] = '/product/open/:slug';
$routes['/plafon-linha-led/{slug}'] = '/product/open/:slug';
$routes['/arandelas-e-balizadores-linha-led/{slug}'] = '/product/open/:slug';
$routes['/refletores-linha-led/{slug}'] = '/product/open/:slug';
$routes['/embutido-de-solo-linha-led/{slug}'] = '/product/open/:slug';
$routes['/ventiladores/{slug}'] = '/product/open/:slug';
$routes['/lampadas-de-led/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-bulbo/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-dicroica/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-par20/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-par30/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-ar70/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-ar111/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-r7s/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-g9/{slug}'] = '/product/open/:slug';
$routes['/lampada-de-led-vela-e14/{slug}'] = '/product/open/:slug';
$routes['/plafon-linha-led-sobrepor/{slug}'] = '/product/open/:slug';
$routes['/plafon-linha-led-embutir/{slug}'] = '/product/open/:slug';
$routes['/plafon-linha-led-sobrepor/{slug}'] = '/product/open/:slug';
$routes['/plafon-linha-led-embutir/{slug}'] = '/product/open/:slug';
$routes['/arandelas-e-balizadores-linha-led-internos/{slug}'] = '/product/open/:slug';
$routes['/arandelas-e-balizadores-linha-led-externos/{slug}'] = '/product/open/:slug';
$routes['/outlet/{slug}'] = '/product/open/:slug';
$routes['/spots-linha-led-embutir/{slug}'] = '/product/open/:slug';
$routes['/spots-linha-led-sobrepor/{slug}'] = '/product/open/:slug';
